CAUTION: Heisenbug.
For no apparent reason, wso2carbon.jks under config/ stopped working, and threw an exception:


Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.Validator
Exception: PKIX path building failed: sun.security.provider.certpath.SunCertPath
BuilderException: unable to find valid certification path to requested target


I spent hours trying to work around it and eventually it resolved itself.  Grr...  There's a note about this in config/, as I assume it will happen again.


The good news is, with a fresh checkout into a new workspace, and with the newest version of registryclient.jar placed into my unmanaged library area, the "phantom jar" bug from Friday is apparently done with.  When agent is online, portal is now able to start a run, it initializes... runs.. and then reports finished.  Yay!